# Generated by Django 6.0.4 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="completion_message",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="test",
            name="completion_link_url",
            field=models.URLField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="test",
            name="completion_link_label",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
