# Generated by Django 6.0.4 on 2026-10-02 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_test_completion_screen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('google_email', models.CharField(blank=True, max_length=320)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=32)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('work_id', models.CharField(max_length=32)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_posts', to='assessments.test')),
            ],
            options={
                'ordering': ['posted_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('test', 'course_id'), name='one_classroom_post_per_class')],
            },
        ),
    ]
