# Generated by Django 6.0.4 on 2026-10-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='blank_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='match_extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='match_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('FB', 'Fill in the Blank'), ('MT', 'Matching')], default='MC', max_length=2),
        ),
    ]
