# Generated by Django 6.0.4 on 2026-05-11 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_quiz_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
