# Generated by Django 6.0.4 on 2026-05-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_flashcardset_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knew_it', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.flashcard')),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.flashcardset')),
            ],
        ),
    ]
