# Generated by Django 6.0.4 on 2026-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_flashcardresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
