# Generated by Django 6.0.4 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_flashcardresponse_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="question_type",
            field=models.CharField(
                choices=[("MC", "Multiple Choice"), ("SA", "Short Answer")],
                default="MC",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="pollresponse",
            name="text_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="option_a",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="option_b",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pollresponse",
            name="selected_option",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
