# Generated by Django 6.0.4 on 2026-08-31
#
# Three steps on purpose. A callable default is evaluated once, so adding a
# unique UUID column in a single step writes the SAME value to every existing
# row and the unique index then fails to build. Instead: add the column
# nullable, give each existing row its own UUID, then apply the constraint.

import uuid

from django.db import migrations, models


def fill_public_ids(apps, schema_editor):
    PollQuestion = apps.get_model("polls", "PollQuestion")

    for question in PollQuestion.objects.filter(public_id__isnull=True):
        question.public_id = uuid.uuid4()
        question.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_short_answer_poll_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="public_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(fill_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pollquestion",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
