# Generated by Django 6.0.4 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_pollquestion_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="answer_round",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
